BusinessManagementSystemApp/BusinessManagementSystemApp/Controllers/ProductController.cs
using BusinessManagementSystemApp.BLL.BLL;
using BusinessManagementSystemApp.Models.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;

namespace BusinessManagementSystemApp.Controllers
{
    public class ProductController : Controller
    {
        CategoryManager _categoryManager = new CategoryManager();
        ProductManager _productManager = new ProductManager();
        Product product = new Product();
        
        public ActionResult Index()
        {
            List<ProductViewModel> products = _productManager.GetProducts().Select(c => new ProductViewModel { ProductId = c.ProductId, ProductName = c.ProductName, ProductCode = c.ProductCode, CategoryName = c.Category.CategoryName, ImagePath = c.Image, ReorderLevel = c.ReorderLevel, Date = c.Date }).ToList();
            ProductViewModel productViewModel = new ProductViewModel();
            productViewModel.Products = products;
            return View(productViewModel);
        }
        [HttpPost]
        public ActionResult Index(ProductViewModel productViewModel)
        {
            if(productViewModel.SearchText!=null && productViewModel.SearchText != "")
            {
                List<ProductViewModel> products = _productManager.SearchProducts(productViewModel).Select(c => new ProductViewModel { ProductId = c.ProductId, ProductName = c.ProductName, ProductCode = c.ProductCode, CategoryName = c.Category.CategoryName, ImagePath = c.Image, ReorderLevel = c.ReorderLevel, Date = c.Date }).ToList();
                if (products.Any())
                {
                    ProductViewModel product = new ProductViewModel();
                    product.Products = products;
                    return View(product);
                }
                else
                {
                    Response.Write("<script>alert('Search not found!');</script>");
                    return View();
                }
            }
            else
            {
                List<ProductViewModel> products = _productManager.GetProducts().Select(c => new ProductViewModel { ProductId = c.ProductId, ProductName = c.ProductName, ProductCode = c.ProductCode, CategoryName = c.Category.CategoryName, ImagePath = c.Image, ReorderLevel = c.ReorderLevel, Date = c.Date }).ToList();
                ProductViewModel productViewModel1 = new ProductViewModel();
                productViewModel1.Products = products;
                return View(productViewModel1);
            }
        }
        public ActionResult SaveProduct()
        {
            var categories = _categoryManager.GetCategories();
            ViewBag.Categories = new SelectList(categories, "CategoryId", "CategoryName");
            return View();
        }
        [HttpPost]
        public ActionResult SaveProduct(ProductViewModel productViewModel, HttpPostedFileBase image)
        {
            var categories = _categoryManager.GetCategories();
            ViewBag.Categories = new SelectList(categories, "CategoryId", "CategoryName");
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(image.FileName);
                    string extension = Path.GetExtension(image.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    productViewModel.ImagePath = "~/Resourses/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/Resourses/"), fileName);
                    image.SaveAs(fileName);
                }
                else
                {
                    productViewModel.ImagePath = "~/Resourses/ImageNotFound.jpg";
                }
                product.ProductName = productViewModel.ProductName;
                product.ProductCode = productViewModel.ProductCode;
                product.CategoryId = productViewModel.CategoryId;
                product.Image = productViewModel.ImagePath;
                product.ReorderLevel = productViewModel.ReorderLevel;
                product.Description = productViewModel.Description;
                product.IsActive = productViewModel.IsActive;
                product.Date = productViewModel.Date;
                productViewModel.ActionType = "Insert";
                if (_productManager.IsExistProduct(productViewModel) == false)
                {
                    if (_productManager.SaveProduct(product))
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.Message = "Failed";
                    }
                }
                else
                {
                    ViewBag.Message = "This product is already exist!";
                }
            }
            return View(productViewModel);
        }
        public ActionResult UpdateProduct(int id)
        {
            if (id > 0)
            {
                product.ProductId = id;
                var aProduct = _productManager.GetProductById(product);
                if (aProduct != null)
                {
                    ProductViewModel productViewModel = new ProductViewModel();
                    productViewModel.ProductId = aProduct.ProductId;
                    productViewModel.ProductName = aProduct.ProductName;
                    productViewModel.ProductCode = aProduct.ProductCode;
                    productViewModel.CategoryId = aProduct.CategoryId;
                    productViewModel.ImagePath = aProduct.Image;
                    productViewModel.ReorderLevel = aProduct.ReorderLevel;
                    productViewModel.Description = aProduct.Description;
                    productViewModel.IsActive = aProduct.IsActive;
                    productViewModel.Date = aProduct.Date;

                    var categories = _categoryManager.GetCategories();
                    ViewBag.Categories = new SelectList(categories, "CategoryId", "CategoryName");
                    return View(productViewModel);
                }
                else
                {
                    return HttpNotFound();
                }
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View();
        }
        [HttpPost]
        public ActionResult UpdateProduct(ProductViewModel productViewModel,HttpPostedFileBase image)
        {
            var categories = _categoryManager.GetCategories();
            ViewBag.Categories = new SelectList(categories, "CategoryId", "CategoryName");
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(image.FileName);
                    string extension = Path.GetExtension(image.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    productViewModel.ImagePath = "~/Resourses/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/Resourses/"), fileName);
                    image.SaveAs(fileName);
                }
                else
                {
                    productViewModel.ImagePath = "~/Resourses/ImageNotFound.jpg";
                }
                product.ProductId = productViewModel.ProductId;
                product = _productManager.GetProductById(product);
                if (product != null)
                {
                    product.ProductName = productViewModel.ProductName;
                    product.ProductCode = productViewModel.ProductCode;
                    product.CategoryId = productViewModel.CategoryId;
                    product.Image = productViewModel.ImagePath;
                    product.ReorderLevel = productViewModel.ReorderLevel;
                    product.Description = productViewModel.Description;
                    product.IsActive = productViewModel.IsActive;
                    product.Date = productViewModel.Date;
                    productViewModel.ActionType = "Update";
                    if (_productManager.IsExistProduct(productViewModel)==false)
                    {
                        if (_productManager.UpdateProduct(product))
                        {
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            ViewBag.Message = "Operation Failed!";
                        }
                    }
                    else
                    {
                        ViewBag.Message = "This product is already exist!";
                    }
                }
            }
            return View(productViewModel);
        }
        public ActionResult ProductDetails(int id)
        {
            if (id > 0)
            {
                product.ProductId = id;
                product = _productManager.GetProductById(product);
                if (product != null)
                {
                    ProductViewModel productViewModel = new ProductViewModel();
                    productViewModel.ProductId = product.ProductId;
                    productViewModel.ProductName = product.ProductName;
                    productViewModel.ProductCode = product.ProductCode;
                    productViewModel.CategoryId = product.CategoryId;
                    productViewModel.CategoryName = product.Category.CategoryName;
                    productViewModel.ImagePath = product.Image;
                    productViewModel.ReorderLevel = product.ReorderLevel;
                    productViewModel.Description = product.Description;
                    productViewModel.IsActive = product.IsActive;

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/Product/DeleteProduct.cshtml
@model BusinessManagementSystemApp.Models.Models.ProductViewModel
@{
    ViewBag.Title = "DeleteProduct";
}

<div class="container" style="width:70%;margin-top:3%;">
    <div class="form-group row">
        <a style="margin-top:2%" href="/Product/Index" class="btn btn-info"><i class="glyphicon glyphicon-list"></i> Product List</a><hr />
        <h3 class="text-danger">Are you sure to delete <b style="background-color:yellow;"><u>'@Model.ProductName'</u></b> product?</h3>
    </div>
</div>
<div class="container">
    <h3 class="text-danger" align="center">
        @ViewBag.Message
    </h3>
</div>
@if (Model != null)
{
<form method="post">
    <input type="hidden" name="ProductId" value="@Model.ProductId" />
    <input type="hidden" name="IsActive" value="False" />
    <input type="hidden" name="Date" value="@DateTime.Now.ToShortDateString()" />
    <div class="container" style="width:80%; margin-top:3%">
        <div class="col-md-8">
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Product Name</label>
                </div>
                <div class="col-md-5">
                    @Html.DisplayFor(c => c.ProductName, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Product Code</label>
                </div>
                <div class="col-md-5">
                    @Html.DisplayFor(c => c.ProductCode, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Category</label>
                </div>
                <div class="col-md-5">
                    @Html.DisplayFor(c => c.CategoryName, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Reorder Level</label>
                </div>
                <div class="col-md-5">
                    @Html.DisplayFor(c => c.ReorderLevel, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Description</label>
                </div>
                <div class="col-md-5">
                    @Html.DisplayFor(c => c.Description, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">

                </div>
                <div class="col-md-5">
                    <input type="submit" class="btn btn-danger" value="Delete Confirm" />
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group row">
                <img src="@Url.Content(Model.ImagePath)" width="90%" height="150" style="border:1px solid red" />
            </div>
        </div>
    </div>
</form>
    
}

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/Product/Index.cshtml
@model BusinessManagementSystemApp.Models.Models.ProductViewModel
@{
    ViewBag.Title = "Index";
}

<div class="form-group">
    <h3 align="center"><b><u>Product List</u></b></h3>
</div>
<div class="container" style="margin-top:6%;">
    <form method="post">
        <div class="form-group row">
            <div class="col-md-6">
                <a style="margin-top:2%" href="/Product/SaveProduct" class="btn btn-info"><i class="glyphicon glyphicon-new-window"></i> <b>New Product</b></a>
            </div>
            <div class="col-md-3">
                @Html.TextBoxFor(c => c.SearchText, new { @class = "form-control", placeholder = "Search Product" })
            </div>
            <div class="col-md-3">
                <input type="submit" value="Search" class="btn btn-block btn-primary" />
            </div>
        </div>
    </form>
</div>
<div class="container">
    <div class="form-group row">
        <div class="col-md-12">
            <table class="table table-hover table-bordered table-striped table-responsive">
                <thead style="background-color:teal; color:white; text-align:center; font-weight:bold">
                    <tr>
                        <td>SL</td>
                        <td>Product Name</td>
                        <td>Code</td>
                        <td>Category</td>
                        <td>Reorder Level</td>
                        <td>Edit</td>
                        <td>Details</td>
                        <td>Delete</td>
                    </tr>
                </thead>
                @if (Model != null)
                {
                    <tbody style="text-align:center; font-weight:bold">
                        @{ int sl = 1;}
                        @foreach (var product in Model.Products)
                        {
                            <tr>
                                <td>@(sl++)</td>
                                <td>@product.ProductName</td>
                                <td>@product.ProductCode</td>
                                <td>@product.CategoryName</td>
                                <td>@product.ReorderLevel</td>
                                <td><a href="/Product/UpdateProduct?id=@product.ProductId" class="btn btn-primary"><i class="glyphicon glyphicon-pencil"></i></a></td>
                                <td><a href="/Product/ProductDetails?id=@product.ProductId" class="btn btn-warning"><i class="glyphicon glyphicon-th-list"></i></a></td>
                                <td><a href="/Product/DeleteProduct?id=@product.ProductId" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i></a></td>
                            </tr>
                        }
                    </tbody>
                }
            </table>
        </div>
    </div>
</div>

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/Product/SaveProduct.cshtml
@model BusinessManagementSystemApp.Models.Models.ProductViewModel
@{
    ViewBag.Title = "SaveProduct";
}

<div class="container">
    <div class="row">
        <a style="margin-top:2%" href="/Product/Index" class="btn btn-info"><i class="glyphicon glyphicon-list"></i> Product List</a><hr />
    </div>
</div>
<div class="container">
    <h3 class="text-danger" align="center">@ViewBag.Message</h3>
</div>
@using (Html.BeginForm("SaveProduct", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="hidden" name="IsActive" value="True" />
    <input type="hidden" name="Date" value="@DateTime.Now.ToShortDateString()" />
    <div class="container" style="width:80%; margin-top:3%">
        <div class="col-md-10">
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Product Name</label>
                </div>
                <div class="col-md-5">
                    @Html.TextBoxFor(c => c.ProductName, new { @class = "form-control", placeholder = "Enter product name" })
                    @Html.ValidationMessageFor(c => c.ProductName, null, new { @class="text-danger"})
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Product Code</label>
                </div>
                <div class="col-md-5">
                    @Html.TextBoxFor(c => c.ProductCode, new { @class = "form-control", placeholder = "Enter product code" })
                    @Html.ValidationMessageFor(c => c.ProductCode, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Categories</label>
                </div>
                <div class="col-md-5">
                    @Html.DropDownListFor(c => c.CategoryId, ViewBag.Categories as SelectList, "--Select--", new { @class = "form-control" })
                </div>
                <div class="col-md-2">
                    <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#myModal"><i class="glyphicon glyphicon-new-window"><b> Add</b></i></a>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Image</label>
                </div>
                <div class="col-md-5">
                    <input type="file" class="form-control" name="image"/>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Reorder Level</label>
                </div>
                <div class="col-md-5">
                    @Html.TextBoxFor(c => c.ReorderLevel, new { @class = "form-control", placeholder = "Enter product reorder level" })
                    @Html.ValidationMessageFor(c => c.ReorderLevel, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Description</label>
                </div>
                <div class="col-md-5">
                    @Html.TextAreaFor(c => c.Description, new { @class = "form-control", placeholder = "Enter product description" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">

                </div>
                <div class="col-md-5">
                    <input type="submit" class="btn btn-block btn-success" value="Save" />
                </div>
            </div>
        </div>
        @*<div class="col-md-4">fjdklf</div>*@
    </div>
}
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
                <h3 class="modal-title text-info">Save new category (:-</h3>
            </div>
            <div class="modal-body">
                <form id="myForm">
                    <div class="container">
                        <div class="form-group row">
                            <div class="col-md-3">Category Name</div>
                            <div class="col-md-9">
                                @*@Html.TextBoxFor(c => c.CategoryName, null, new { @class = "form-control", @placeholder = "Category name" })*@
                                <input type="hidden" name="IsActive" value="True" />
                                <input type="hidden" name="Date" value="@DateTime.Now" />
                                <input type="text" class="form-control" placeholder="Category Name" name="CategoryName" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3">Category Code</div>
                            <div class="col-md-9">
                                @*@Html.TextBoxFor(c => c.CategoryCode, null, new { @class = "form-control", @placeholder = "Category code" })*@
                                <input type="text" class="form-control" placeholder="Category Code" name="CategoryCode" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
                <button id="submitBtn" class="btn btn-success">Save</button>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            $("#submitBtn").click(function () {
                debugger
                var data = $("#myForm").serialize();
                $.ajax({
                    type: "POST",
                    url: "/Category/SaveCategory",
                    data: data,
                    success: function () {
                        alert('Saved!');
                        location.reload(true);
                    }
                })
            })
            

        });
    </script>    
    
}

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/Product/UpdateProduct.cshtml
@model BusinessManagementSystemApp.Models.Models.ProductViewModel
@{
    ViewBag.Title = "UpdateProduct";
}

<div class="container">
    <div class="row">
        <a style="margin-top:2%" href="/Product/Index" class="btn btn-info"><i class="glyphicon glyphicon-list"></i> Product List</a><hr />
    </div>
</div>
@if (ViewBag.Message != null)
{
    <h3 class="text-danger" align="center">@ViewBag.Message</h3>
}
@using (Html.BeginForm("UpdateProduct", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    if (Model != null)
    {
        <div class="panel panel-primary">
            <div class="panel-heading">Update Product</div>
            <div class="container" style="margin:1%">
                <input type="hidden" name="ProductId" value="@Model.ProductId" />
                <input type="hidden" name="IsActive" value="True" />
                <input type="hidden" name="Date" value="@DateTime.Now.ToShortDateString()" />
                <div class="container" style="width:80%; margin-top:3%">
                    <div class="col-md-9">
                        <div class="form-group row">
                            <div class="col-md-2"></div>
                            <div class="col-md-3">
                                <label>Product Name</label>
                            </div>
                            <div class="col-md-5">
                                @Html.TextBoxFor(c => c.ProductName, new { @class = "form-control" })
                                @Html.ValidationMessageFor(c => c.ProductName, null, new { @class="text-danger"})
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-2"></div>
                            <div class="col-md-3">
                                <label>Product Code</label>
                            </div>
                            <div class="col-md-5">
                                @Html.TextBoxFor(c => c.ProductCode, new { @class = "form-control" })
                                @Html.ValidationMessageFor(c => c.ProductCode, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-2"></div>
                            <div class="col-md-3">
                                <label>Category</label>
                            </div>
                            <div class="col-md-5">
                                @Html.DropDownListFor(c => c.CategoryId, ViewBag.Categories as SelectList, "--Select--", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-2"></div>
                            <div class="col-md-3">
                                <label>Image</label>
                            </div>
                            <div class="col-md-5">
                                <input type="file" name="image" class="form-control"/>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-2"></div>
                            <div class="col-md-3">
                                <label>Reorder Level</label>
                            </div>
                            <div class="col-md-5">
                                @Html.TextBoxFor(c => c.ReorderLevel, new { @class = "form-control" })
                                @Html.ValidationMessageFor(c => c.ReorderLevel, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-2"></div>
                            <div class="col-md-3">
                                <label>Description</label>
                            </div>
                            <div class="col-md-5">
                                @Html.TextAreaFor(c => c.Description, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-2"></div>
                            <div class="col-md-3">

                            </div>
                            <div class="col-md-5">
                                <input type="submit" class="btn btn-block btn-success" value="Update" />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group row">
                            <img src="@Url.Content(Model.ImagePath)" width="90%" height="200" style="border:1px solid red" />
                            <h4 class="text-info" align="center">Image</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
}