BusinessManagementSystemApp/BusinessManagementSystemApp/Controllers/SupplierController.cs
using BusinessManagementSystemApp.BLL.BLL;
using BusinessManagementSystemApp.Models.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BusinessManagementSystemApp.Controllers
{
    public class SupplierController : Controller
    {
        public string fileName = "";
        Supplier supplier = new Supplier();
        SupplierManager _supplierManager = new SupplierManager();

        public ActionResult Index()
        {
            List<SupplierViewModel> suppliers = _supplierManager.GetSuppliers().Select(c => new SupplierViewModel { SupplierId = c.SupplierId, SupplierName = c.SupplierName, SupplierCode = c.SupplierCode, Address = c.Address, Email = c.Email, Contact = c.Contact, ContactPerson = c.ContactPerson, LogoPath = c.LogoPath, IsActive = c.IsActive, Date = c.Date }).ToList();
            SupplierViewModel supplierViewModel = new SupplierViewModel();
            supplierViewModel.Suppliers = suppliers;
            return View(supplierViewModel);
        }
        [HttpPost]
        public ActionResult Index(SupplierViewModel supplierViewModel)
        {
            if (supplierViewModel.SearchText != string.Empty && supplierViewModel.SearchText != null)
            {
                List<SupplierViewModel> suppliers = _supplierManager.SearchSupplier(supplierViewModel).Select(c => new SupplierViewModel { SupplierId = c.SupplierId, SupplierName = c.SupplierName, SupplierCode = c.SupplierCode, Address = c.Address, Email = c.Email, Contact = c.Contact, ContactPerson = c.ContactPerson, LogoPath = c.LogoPath, IsActive = c.IsActive, Date = c.Date }).ToList();
                SupplierViewModel aSupplierViewModel = new SupplierViewModel();
                aSupplierViewModel.Suppliers = suppliers;
                return View(aSupplierViewModel);
            }
            else
            {
                List<SupplierViewModel> suppliers = _supplierManager.GetSuppliers().Select(c => new SupplierViewModel { SupplierId = c.SupplierId, SupplierName = c.SupplierName, SupplierCode = c.SupplierCode, Address = c.Address, Email = c.Email, Contact = c.Contact, ContactPerson = c.ContactPerson, LogoPath = c.LogoPath, IsActive = c.IsActive, Date = c.Date }).ToList();
                SupplierViewModel supplierViewModel1 = new SupplierViewModel();
                supplierViewModel1.Suppliers = suppliers;
                return View(supplierViewModel1);
            }
        }
        public ActionResult SaveSupplier()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SaveSupplier(SupplierViewModel supplierViewModel, HttpPostedFileBase logo)
        {
            if (ModelState.IsValid)
            {
                if (logo != null)
                {
                    fileName = Path.GetFileNameWithoutExtension(logo.FileName);
                    string extension = Path.GetExtension(logo.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    supplierViewModel.LogoPath = "~/Resourses/" + fileName;
                }
                supplierViewModel.ActionType = "Insert";
                if (_supplierManager.IsExistSupplier(supplierViewModel) == false)
                {
                    supplier.SupplierId = supplierViewModel.SupplierId;
                    supplier.SupplierName = supplierViewModel.SupplierName;
                    supplier.SupplierCode = supplierViewModel.SupplierCode;
                    supplier.Address = supplierViewModel.Address;
                    supplier.Email = supplierViewModel.Email;
                    supplier.Contact = supplierViewModel.Contact;
                    supplier.ContactPerson = supplierViewModel.ContactPerson;
                    supplier.LogoPath = supplierViewModel.LogoPath;
                    supplier.IsActive = supplierViewModel.IsActive;
                    supplier.Date = supplierViewModel.Date;
                    if (_supplierManager.SaveSupplier(supplier))
                    {
                        fileName = Path.Combine(Server.MapPath("~/Resourses/"), fileName);
                        logo.SaveAs(fileName);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.Message = "Operation Failed!";
                    }
                }
                else
                {
                    ViewBag.Message = "This supplier is already exist!";
                }
            }
            else
            {
                ViewBag.Message = "Input validation error!";
            }
            return View(supplierViewModel);
        }
        public ActionResult UpdateSupplier(int id)
        {
            if (id > 0)
            {
                supplier.SupplierId = id;
                var aSupplier = _supplierManager.GetSupplierById(supplier);
                SupplierViewModel supplierViewModel = new SupplierViewModel();
                supplierViewModel.SupplierId = aSupplier.SupplierId;
                supplierViewModel.SupplierName = aSupplier.SupplierName;
                supplierViewModel.SupplierCode = aSupplier.SupplierCode;
                supplierViewModel.Address = aSupplier.Address;
                supplierViewModel.Email = aSupplier.Email;
                supplierViewModel.Contact = aSupplier.Contact;
                supplierViewModel.ContactPerson = aSupplier.ContactPerson;
                supplierViewModel.LogoPath = aSupplier.LogoPath;
                supplierViewModel.IsActive = aSupplier.IsActive;
                supplierViewModel.Date = aSupplier.Date;
                return View(supplierViewModel);
            }
            else
            {
                return HttpNotFound();
            }
        }
        [HttpPost]
        public ActionResult UpdateSupplier(SupplierViewModel supplierViewModel,HttpPostedFileBase logo)
        {
            if (ModelState.IsValid)
            {
                string fileName = "";
                if (logo != null)
                {
                    fileName = Path.GetFileNameWithoutExtension(logo.FileName);
                    string extension = Path.GetExtension(logo.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    supplierViewModel.LogoPath = "~/Resourses/" + fileName;
                }
                supplierViewModel.ActionType = "Update";
                if (_supplierManager.IsExistSupplier(supplierViewModel) == false)
                {
                    supplier.SupplierId = supplierViewModel.SupplierId;
                    supplier = _supplierManager.GetSupplierById(supplier);
                    if (supplier != null)
                    {
                        supplier.SupplierId = supplierViewModel.SupplierId;
                        supplier.SupplierName = supplierViewModel.SupplierName;
                        supplier.SupplierCode = supplierViewModel.SupplierCode;
                        supplier.Address = supplierViewModel.Address;
                        supplier.Email = supplierViewModel.Email;
                        supplier.Contact = supplierViewModel.Contact;
                        supplier.ContactPerson = supplierViewModel.ContactPerson;
                        supplier.LogoPath = supplierViewModel.LogoPath;
                        supplier.IsActive = supplierViewModel.IsActive;
                        supplier.Date = supplierViewModel.Date;
                        if (_supplierManager.UpdateSupplier(supplier))
                        {
                            fileName = Path.Combine(Server.MapPath("~/Resourses/"), fileName);
                            logo.SaveAs(fileName);
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            ViewBag.Message = "Operation Failed!";
                        }
                    }
                    else
                    {
                        ViewBag.Message = "Supplier Not Found!";
                    }
                }
            }
            else
            {
                ViewBag.Message = "Input Validation Error!";
            }
            return View(supplierViewModel);
        }
        public ActionResult SupplierDetails(int id)
        {
            if (id > 0)
            {
                supplier.SupplierId = id;
                var aSupplier = _supplierManager.GetSupplierById(supplier);
                if (aSupplier != null)
                {
                    SupplierViewModel supplierViewModel = new SupplierViewModel();
                    supplierViewModel.SupplierId = aSupplier.SupplierId;
                    supplierViewModel.SupplierName = aSupplier.SupplierName;
                    supplierViewModel.SupplierCode = aSupplier.SupplierCode;
                    supplierViewModel.Address = aSupplier.Address;
                    supplierViewModel.Email = aSupplier.Email;
                    supplierViewModel.Contact = aSupplier.Contact;
                    supplierViewModel.ContactPerson = aSupplier.ContactPerson;
                    supplierViewModel.LogoPath = aSupplier.LogoPath;
                    supplierViewModel.IsActive = aSupplier.IsActive;
                    supplierViewModel.Date = aSupplier.Date;
                    return View(supplierViewModel);
                }
                else
                {
                    ViewBag.Message = "Supplier Not Found!";
                }
            }
            else
            {
                return HttpNotFound();
            }
            return View();
        }
        public ActionResult DeleteSupplier(int id)
        {
            if (id > 0)
            {
                supplier.SupplierId = id;

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/Supplier/DeleteSupplier.cshtml
@model BusinessManagementSystemApp.Models.Models.SupplierViewModel
@{
                /**/

                ViewBag.Title = "DeleteSupplier";
}

<div class="container">
    <div class="row">
        <a style="margin-top:2%" href="/Supplier/Index" class="btn btn-info"><i class="glyphicon glyphicon-list"></i> Supplier List</a><hr />
        <h3 class="text-danger">Are you sure to delete <b style="background-color:yellow;"><u>'@Model.SupplierName'</u></b> supplier?</h3>
    </div>
</div>

@if (ViewBag.Message != null)
{
    <h3 class="text-danger" align="center">@ViewBag.Message</h3>
}
    <form method="post">
        @if (Model != null)
        {
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h4 class="text-danger">Delete Supplier</h4>
            </div>
            <input type="hidden" name="SupplierId" value="@Model.SupplierId" />
            <input type="hidden" name="IsActive" value="False" />
            <input type="hidden" name="Date" value="@DateTime.Now.ToShortDateString()" />
            <div class="container" style="width:80%; margin-top:3%">
                <div class="col-md-9">
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Supplier Name</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.SupplierName, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Supplier Code</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.SupplierCode, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Address</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.Address, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Email</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.Email, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Contact</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.Contact, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Contact Person</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.ContactPerson, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">

                        </div>
                        <div class="col-md-5">
                            <input type="submit" class="btn btn-block btn-danger" value="Confirm Delete" />
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group row">
                        <img src="@Url.Content(Model.LogoPath)" width="90%" height="200" style="border:1px solid red" />
                        <h4 class="text-info" align="center">Logo</h4>
                    </div>
                </div>
            </div>
        </div>
        }
    </form>

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/Supplier/Index.cshtml
@model BusinessManagementSystemApp.Models.Models.SupplierViewModel
@{
    ViewBag.Title = "Index";
}

<div class="form-group">
    <h3 align="center"><b><u>Supplier List</u></b></h3>
</div>
<div class="container" style="margin-top:6%;">
    <form method="post">
        <div class="form-group row">
            <div class="col-md-6">
                <a style="margin-top:2%" href="/Supplier/SaveSupplier" class="btn btn-info"><i class="glyphicon glyphicon-new-window"></i> <b>New Supplier</b></a>
            </div>
            <div class="col-md-3">
                @Html.TextBoxFor(c => c.SearchText, new { @class = "form-control", placeholder = "Search Supplier" })
            </div>
            <div class="col-md-3">
                <input type="submit" value="Search" class="btn btn-block btn-primary" />
            </div>
        </div>
    </form>
</div>
@if (Model != null)
{
    <div class="container">
        <div class="form-group row">
            <div class="col-md-12">
                <table class="table table-hover table-bordered table-striped table-responsive">
                    <thead style="background-color:teal; color:white; text-align:center; font-weight:bold">
                        <tr>
                            <td>SL</td>
                            <td>Supplier Name</td>
                            <td>Code</td>
                            <td>Address</td>
                            <td>Email</td>
                            <td>Contact Number</td>
                            <td>Contact Person</td>
                            <td>Edit</td>
                            <td>Details</td>
                            <td>Delete</td>
                        </tr>
                    </thead>
                    <tbody style="text-align:center; font-weight:bold">
                        @{ int sl = 1;}
                        @foreach (var supplier in Model.Suppliers)
                        {
                            <tr>
                                <td>@(sl++)</td>
                                <td>@supplier.SupplierName</td>
                                <td>@supplier.SupplierCode</td>
                                <td>@supplier.Address</td>
                                <td>@supplier.Email</td>
                                <td>@supplier.Contact</td>
                                <td>@supplier.ContactPerson</td>
                                <td><a href="/Supplier/UpdateSupplier?id=@supplier.SupplierId" class="btn btn-primary"><i class="glyphicon glyphicon-pencil"></i></a></td>
                                <td><a href="/Supplier/SupplierDetails?id=@supplier.SupplierId" class="btn btn-warning"><i class="glyphicon glyphicon-th-list"></i></a></td>
                                <td><a href="/Supplier/DeleteSupplier?id=@supplier.SupplierId" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i></a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/Supplier/SaveSupplier.cshtml
@model BusinessManagementSystemApp.Models.Models.SupplierViewModel
@{
    ViewBag.Title = "SaveSupplier";
}

<div class="container">
    <div class="row">
        <a style="margin-top:2%" href="/Supplier/Index" class="btn btn-info"><i class="glyphicon glyphicon-list"></i> Supplier List</a><hr />
    </div>
</div>
<div class="container">
    <h3 class="text-danger" align="center">@ViewBag.Message</h3>
</div>
@using (Html.BeginForm("SaveSupplier", "Supplier", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="panel panel-primary">
    <div class="panel-heading">
        Save New Supplier
    </div>
    <input type="hidden" name="IsActive" value="True" />
    <input type="hidden" name="Date" value="@DateTime.Now.ToShortDateString()" />
    <div class="container" style="width:80%; margin-top:3%">
        <div class="col-md-10">
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Supplier Name</label>
                </div>
                <div class="col-md-5">
                    @Html.TextBoxFor(c => c.SupplierName, new { @class = "form-control", placeholder = "Enter supplier name" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Supplier Code</label>
                </div>
                <div class="col-md-5">
                    @Html.TextBoxFor(c => c.SupplierCode, new { @class = "form-control", placeholder = "Enter supplier code" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Address</label>
                </div>
                <div class="col-md-5">
                    @Html.TextBoxFor(c => c.Address, new { @class = "form-control", placeholder = "Enter Address" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Logo</label>
                </div>
                <div class="col-md-5">
                    <input type="file" class="form-control" name="logo" required />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Email</label>
                </div>
                <div class="col-md-5">
                    @Html.TextBoxFor(c => c.Email, new { @class = "form-control", placeholder = "Enter email address" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Contact</label>
                </div>
                <div class="col-md-5">
                    @Html.TextBoxFor(c => c.Contact, new { @class = "form-control", placeholder = "Enter contact number" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">
                    <label>Contact Person</label>
                </div>
                <div class="col-md-5">
                    @Html.TextBoxFor(c => c.ContactPerson, new { @class = "form-control", placeholder = "Enter contact person number" })
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2"></div>
                <div class="col-md-3">

                </div>
                <div class="col-md-5">
                    <input type="submit" class="btn btn-block btn-success" value="Save" />
                </div>
            </div>
        </div>
        @*<div class="col-md-4">fjdklf</div>*@
    </div>
</div>
}

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/Supplier/SupplierDetails.cshtml
@model BusinessManagementSystemApp.Models.Models.SupplierViewModel

@{
                /**/

                ViewBag.Title = "SupplierDetails";
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>

<div class="container">
    <div class="row">
        <a style="margin-top:2%" href="/Supplier/Index" class="btn btn-info"><i class="glyphicon glyphicon-list"></i> Supplier List</a><hr />
    </div>
</div>
@if (ViewBag.Message != null)
{
    <h3 class="text-danger" align="center">@ViewBag.Message</h3>
}
@if (Model != null)
{
    <div class="panel panel-primary">
        <div class="panel-heading">Supplier Details</div>
        <div class="container" style="margin:1%">
            <input type="hidden" name="IsActive" value="True" />
            <input type="hidden" name="Date" value="@DateTime.Now.ToShortDateString()" />
            <div class="container" style="width:80%; margin-top:3%">
                <div class="col-md-9">
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Supplier Name</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.SupplierName, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Supplier Code</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.SupplierCode, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Address</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.Address, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Email</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.Email, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Contact</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.Contact, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Contact Person</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.ContactPerson, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">

                        </div>
                        <div class="col-md-5">
                            <a href="/Supplier/UpdateSupplier?id=@Model.SupplierId" class="btn btn-block btn-success">Edit</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group row">
                        <img src="@Url.Content(Model.LogoPath)" width="90%" height="200" style="border:1px solid red" />
                        <h4 class="text-info" align="center">Logo</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/Supplier/UpdateSupplier.cshtml
@model BusinessManagementSystemApp.Models.Models.SupplierViewModel
@{
    ViewBag.Title = "UpdateSupplier";
}

<div class="container">
    <div class="row">
        <a style="margin-top:2%" href="/Supplier/Index" class="btn btn-info"><i class="glyphicon glyphicon-list"></i> Supplier List</a><hr />
    </div>
</div>
@if (ViewBag.Message != null)
{
    <h3 class="text-danger" align="center">@ViewBag.Message</h3>
}
@using (Html.BeginForm("UpdateSupplier", "Supplier", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    if (Model != null)
    {
        <div class="panel panel-info">
            <div class="panel-heading">
                <h4 class="text-primary">
                    Update Supplier
                </h4>
            </div>
            <input type="hidden" name="SupplierId" value="@Model.SupplierId" />
            <input type="hidden" name="IsActive" value="True" />
            <input type="hidden" name="Date" value="@DateTime.Now.ToShortDateString()" />
            <div class="container" style="width:80%; margin-top:3%">
                <div class="col-md-9">
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Supplier Name</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.SupplierName, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Supplier Code</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.SupplierCode, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Address</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.Address, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Logo</label>
                        </div>
                        <div class="col-md-5">
                            <input type="file" class="form-control" name="logo" required />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Email</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.Email, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Contact</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.Contact, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Contact Person</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.ContactPerson, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">

                        </div>
                        <div class="col-md-5">
                            <input type="submit" class="btn btn-block btn-success" value="Update" />
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group row">
                        <img src="@Url.Content(Model.LogoPath)" width="90%" height="200" style="border:1px solid red" />
                        <h4 class="text-info" align="center">Logo</h4>
                    </div>
                </div>
            </div>
        </div>
    }
}