BusinessManagementSystemApp/BusinessManagementSystemApp/Controllers/CustomerController.cs
using AutoMapper;
using BusinessManagementSystemApp.BLL.Manager;
using BusinessManagementSystemApp.Models.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BusinessManagementSystemApp.Controllers
{
    public class CustomerController : Controller
    {
        Customer _customer = new Customer();
        string _fileName = "";
        CustomerManager _customerManager = new CustomerManager();

        public ActionResult Index()
        {
            List<CustomerViewModel> customers = _customerManager.GetCustomers().Select(c => new CustomerViewModel
            {
                Id = c.Id,
                CustomerName = c.CustomerName,
                CustomerCode = c.CustomerCode,
                Address = c.Address,
                Email = c.Email,
                Contact = c.Contact,
                LoyaltyPoint = c.LoyaltyPoint
            }).ToList();
            CustomerViewModel customerViewModel = new CustomerViewModel();
            customerViewModel.Customers = customers;
            return View(customerViewModel);
        }
        [HttpPost]
        public ActionResult Index(CustomerViewModel customerViewModel)
        {
            if(customerViewModel.SearchText!=string.Empty && customerViewModel.SearchText != null)
            {
                var customers = _customerManager.SearchCustomers(customerViewModel).Select(c => new CustomerViewModel
                {
                    Id = c.Id,
                    CustomerName = c.CustomerName,
                    CustomerCode = c.CustomerCode,
                    Address = c.Address,
                    Email = c.Email,
                    Contact = c.Contact,
                    LoyaltyPoint = c.LoyaltyPoint
                }).ToList();
                CustomerViewModel aCustomer = new CustomerViewModel();
                aCustomer.Customers = customers;
                return View(aCustomer);
            }
            else
            {
                List<CustomerViewModel> customers = _customerManager.GetCustomers().Select(c => new CustomerViewModel
                {
                    Id = c.Id,
                    CustomerName = c.CustomerName,
                    CustomerCode = c.CustomerCode,
                    Address = c.Address,
                    Email = c.Email,
                    Contact = c.Contact,
                    LoyaltyPoint = c.LoyaltyPoint
                }).ToList();
                CustomerViewModel aCustomerViewModel = new CustomerViewModel();
                aCustomerViewModel.Customers = customers;
                return View(aCustomerViewModel);
            }
        }
        public ActionResult SaveCustomer()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SaveCustomer(CustomerViewModel customerViewModel,HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    _fileName = Path.GetFileNameWithoutExtension(image.FileName);
                    string extension = Path.GetExtension(image.FileName);
                    _fileName = _fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    customerViewModel.ImagePath= "~/Resourses/" + _fileName;
                }
                customerViewModel.ActionType = "Insert";
                if (_customerManager.IsExistCustomer(customerViewModel) == false)
                {
                    _customer = Mapper.Map<Customer>(customerViewModel);
                    if (_customerManager.SaveCustomer(_customer))
                    {
                        _fileName = Path.Combine(Server.MapPath("~/Resourses/"), _fileName);
                        image.SaveAs(_fileName);
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    ViewBag.Message = "This Customer Is Already Exist!";
                }
            }
            return View(customerViewModel);
        }
        public ActionResult UpdateCustomer(int id)
        {
            _customer.Id = id;
            var aCustomer = _customerManager.GetCustomerById(_customer);
            if (aCustomer == null)
            {
                ViewBag.Message = "No Customer Found!";
                return View();
            }
            CustomerViewModel customerViewModel = new CustomerViewModel();
            customerViewModel = Mapper.Map<CustomerViewModel>(aCustomer);
            return View(customerViewModel);
        }
        [HttpPost]
        public ActionResult UpdateCustomer(CustomerViewModel customerViewModel,HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    _fileName = Path.GetFileNameWithoutExtension(image.FileName);
                    string extension = Path.GetExtension(image.FileName);
                    _fileName = _fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    customerViewModel.ImagePath = "~/Resourses/" + _fileName;
                }
                customerViewModel.ActionType = "Update";
                if (_customerManager.IsExistCustomer(customerViewModel)==false)
                {
                    _customer.Id = customerViewModel.Id;
                    _customer = _customerManager.GetCustomerById(_customer);
                    if (_customer != null)
                    {
                        //_customer = Mapper.Map<Customer>(customerViewModel);
                        _customer.Id = customerViewModel.Id;
                        _customer.CustomerName = customerViewModel.CustomerName;
                        _customer.CustomerCode = customerViewModel.CustomerCode;
                        _customer.Address = customerViewModel.Address;
                        _customer.Email = customerViewModel.Email;
                        _customer.Contact = customerViewModel.Contact;
                        _customer.LoyaltyPoint = customerViewModel.LoyaltyPoint;
                        _customer.ImagePath = customerViewModel.ImagePath;
                        _customer.Date = customerViewModel.Date;
                        _customer.IsActive = customerViewModel.IsActive;
                        if (_customerManager.UpdateCustomer(_customer))
                        {
                            _fileName = Path.Combine(Server.MapPath("~/Resourses/"), _fileName);
                            image.SaveAs(_fileName);
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            ViewBag.Message = "Opps! Your Current Operation Failed.";
                        }
                    }
                    else
                    {
                        ViewBag.Message = "Customer Not Found!";
                    }
                }
                else
                {
                    ViewBag.Message = "This Customer Is Already Exist!";
                }
            }
            return View(customerViewModel);
        }
        public ActionResult CustomerDetails(int id)
        {
            _customer.Id = id;
            var aCustomer = _customerManager.GetCustomerById(_customer);
            if (aCustomer == null)
            {
                ViewBag.Message = "No Customer Found!";
                return View();
            }
            CustomerViewModel customerViewModel = new CustomerViewModel();
            customerViewModel = Mapper.Map<CustomerViewModel>(aCustomer);
            return View(customerViewModel);
        }
        public ActionResult DeleteCustomer(int id)
        {
            _customer.Id = id;
            var aCustomer = _customerManager.GetCustomerById(_customer);
            if (aCustomer == null)
            {
                ViewBag.Message = "No Customer Found!";
                return View();
            }
            CustomerViewModel customerViewModel = new CustomerViewModel();
            customerViewModel = Mapper.Map<CustomerViewModel>(aCustomer);
            return View(customerViewModel);
        }
        [HttpPost]
        public ActionResult DeleteCustomer(CustomerViewModel customerViewModel)
        {
            if (customerViewModel.Id > 0)
            {
                _customer.Id = customerViewModel.Id;
                _customer = _customerManager.GetCustomerById(_customer);
                if (_customer != null)
                {
                    _customer.IsActive = customerViewModel.IsActive;
                    _customer.Date = customerViewModel.Date;
                    if (_customerManager.DeleteCustomer(_customer))
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.Message = "Opps! Operation Failed...";
                    }
                }
                else
                {
                    ViewBag.Message = "No Customer Found!";
                }
            }
            else
            {
                ViewBag.Message = "Operation Failed!";
            }
            return View(customerViewModel);
        }
    }
}

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/Customer/CustomerDetails.cshtml
@model BusinessManagementSystemApp.Models.Models.CustomerViewModel
@{
    /**/

    ViewBag.Title = "CustomerDetails";
}

<div class="container">
    <div class="row">
        <a style="margin-top:2%" href="/Customer/Index" class="btn btn-info"><i class="glyphicon glyphicon-list"></i> Customer List</a><hr />
    </div>
</div>
@if (ViewBag.Message != null)
{
    <h3 class="text-danger" align="center">@ViewBag.Message</h3>
}
@if (Model != null)
{
    <div class="panel panel-info">
        <div class="panel-heading">
            <h4 class="text-primary">
                Show Customer Details
            </h4>
        </div>
        <input type="hidden" name="Id" value="@Model.Id" />
        <input type="hidden" name="IsActive" value="True" />
        <input type="hidden" name="Date" value="@DateTime.Now.ToShortDateString()" />
        <div class="container" style="width:80%; margin-top:3%">
            <div class="col-md-9">
                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label>Customer Name</label>
                    </div>
                    <div class="col-md-5">
                        @Html.TextBoxFor(c => c.CustomerName, new { @class = "form-control", @readonly="readonly" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label>Customer Code</label>
                    </div>
                    <div class="col-md-5">
                        @Html.TextBoxFor(c => c.CustomerCode, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label>Address</label>
                    </div>
                    <div class="col-md-5">
                        @Html.TextBoxFor(c => c.Address, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label>Email</label>
                    </div>
                    <div class="col-md-5">
                        @Html.TextBoxFor(c => c.Email, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label>Contact</label>
                    </div>
                    <div class="col-md-5">
                        @Html.TextBoxFor(c => c.Contact, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label>Loyalty Point</label>
                    </div>
                    <div class="col-md-5">
                        @Html.TextBoxFor(c => c.LoyaltyPoint, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">

                    </div>
                    <div class="col-md-5">
                        <a href="/Customer/UpdateCustomer?id=@Model.Id" class="btn btn-success"><b>Edit</b></a>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group row">
                    <img src="@Url.Content(Model.ImagePath)" width="90%" height="200" style="border:1px solid red" />
                    <h4 class="text-info" align="center">Image</h4>
                </div>
            </div>
        </div>
    </div>
}

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/Customer/DeleteCustomer.cshtml
@model BusinessManagementSystemApp.Models.Models.CustomerViewModel
@{
    ViewBag.Title = "DeleteSupplier";
}

<div class="container">
    <div class="row">
        <a style="margin-top:2%" href="/Customer/Index" class="btn btn-info"><i class="glyphicon glyphicon-list"></i> Customer List</a><hr />
        <h3 class="text-danger">Are you sure to delete <b style="background-color:yellow;"><u>'@Model.CustomerName'</u></b> customer?</h3>
    </div>
</div>

@if (ViewBag.Message != null)
{
    <h3 class="text-danger" align="center">@ViewBag.Message</h3>
}
<form method="post">
    @if (Model != null)
    {
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h4 class="text-danger">Delete Supplier</h4>
            </div>
            <input type="hidden" name="SupplierId" value="@Model.Id" />
            <input type="hidden" name="IsActive" value="False" />
            <input type="hidden" name="Date" value="@DateTime.Now.ToShortDateString()" />
            <div class="container" style="width:80%; margin-top:3%">
                <div class="col-md-9">
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Customer Name</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.CustomerName, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Customer Code</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.CustomerCode, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Address</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.Address, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Email</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.Email, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Contact</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.Contact, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Loyalty Point</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.LoyaltyPoint, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">

                        </div>
                        <div class="col-md-5">
                            <input type="submit" class="btn btn-block btn-danger" value="Confirm Delete" />
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group row">
                        <img src="@Url.Content(Model.ImagePath)" width="90%" height="200" style="border:1px solid red" />
                        <h4 class="text-info" align="center">Image</h4>
                    </div>
                </div>
            </div>
        </div>
    }
</form>

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/Customer/Index.cshtml
@model BusinessManagementSystemApp.Models.Models.CustomerViewModel
@{
    ViewBag.Title = "Index";
}

<form method="post">
    <div class="container">
        <h3 class="text" style="text-align:center">
            <b style="background-color:darkgreen; color:white">Customer List</b>
        </h3>
    </div>
    <div class="container" style="margin-top:3%">
        <div class="form-group row">
            <div class="col-md-9">
                <a href="/Customer/SaveCustomer" class="btn btn-info"><i class="glyphicon glyphicon-new-window"> <b>New Customer</b></i></a>
            </div>
            <div class="col-md-3">
                <input type="text" placeholder="Search.." name="SearchText">
                <button type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-12">
                <table class="table table-bordered table-hover table-striped table-responsive">
                    <thead style="background-color:teal; color:white; text-align:center; font-weight:bold">
                        <tr>
                            <td>SL</td>
                            <td>Customer Name</td>
                            <td>Code</td>
                            <td>Address</td>
                            <td>Email</td>
                            <td>Contact Number</td>
                            <td>Loyalty Point</td>
                            <td>Edit</td>
                            <td>Details</td>
                            <td>Delete</td>
                        </tr>
                    </thead>
                    @if (Model != null && Model.Customers.Count > 0)
                    {
                        <tbody style="text-align:center; font-weight:bold">
                            @{ int sl = 1;}
                            @foreach (var customer in Model.Customers)
                            {
                                <tr>
                                    <td>@(sl++)</td>
                                    <td>@customer.CustomerName</td>
                                    <td>@customer.CustomerCode</td>
                                    <td>@customer.Address</td>
                                    <td>@customer.Email</td>
                                    <td>@customer.Contact</td>
                                    <td>@customer.LoyaltyPoint</td>
                                    <td><a href="/Customer/UpdateCustomer?id=@customer.Id" class="btn btn-primary"><i class="glyphicon glyphicon-pencil"></i></a></td>
                                    <td><a href="/Customer/CustomerDetails?id=@customer.Id" class="btn btn-warning"><i class="glyphicon glyphicon-th-list"></i></a></td>
                                    <td><a href="/Customer/DeleteCustomer?id=@customer.Id" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i></a></td>
                                </tr>
                            }
                        </tbody>
                    }
                </table>
            </div>
        </div>
    </div>
</form>

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/Customer/SaveCustomer.cshtml
@model BusinessManagementSystemApp.Models.Models.CustomerViewModel
@{
    ViewBag.Title = "SaveCustomer";
}

<div class="container">
    <div class="row">
        <a style="margin-top:2%" href="/Customer/Index" class="btn btn-info"><i class="glyphicon glyphicon-list"></i> Customer List</a><hr />
    </div>
</div>
<div class="container">
    <h3 class="text-danger" align="center">@ViewBag.Message</h3>
</div>
@using (Html.BeginForm("SaveCustomer", "Customer", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="panel panel-primary">
        <div class="panel-heading">
            Save New Customer
        </div>
        <input type="hidden" name="IsActive" value="True" />
        <input type="hidden" name="Date" value="@DateTime.Now.ToShortDateString()" />
        <div class="container" style="width:80%; margin-top:3%">
            <div class="col-md-10">
                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label>Customer Name</label>
                    </div>
                    <div class="col-md-5">
                        @Html.TextBoxFor(c => c.CustomerName, new { @class = "form-control", placeholder = "Enter customer name" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label>Customer Code</label>
                    </div>
                    <div class="col-md-5">
                        @Html.TextBoxFor(c => c.CustomerCode, new { @class = "form-control", placeholder = "Enter customer code" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label>Address</label>
                    </div>
                    <div class="col-md-5">
                        @Html.TextBoxFor(c => c.Address, new { @class = "form-control", placeholder = "Enter Address" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label>Image</label>
                    </div>
                    <div class="col-md-5">
                        <input type="file" class="form-control" name="image" required />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label>Email</label>
                    </div>
                    <div class="col-md-5">
                        @Html.TextBoxFor(c => c.Email, new { @class = "form-control", placeholder = "Enter email address" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label>Contact</label>
                    </div>
                    <div class="col-md-5">
                        @Html.TextBoxFor(c => c.Contact, new { @class = "form-control", placeholder = "Enter contact number" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">
                        <label>Loyalty Point</label>
                    </div>
                    <div class="col-md-5">
                        @Html.TextBoxFor(c => c.LoyaltyPoint, new { @class = "form-control", placeholder = "Enter initial loyalty point" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-3">

                    </div>
                    <div class="col-md-5">
                        <input type="submit" class="btn btn-block btn-success" value="Save" />
                    </div>
                </div>
            </div>
            @*<div class="col-md-4">fjdklf</div>*@
        </div>
    </div>
}

BusinessManagementSystemApp/BusinessManagementSystemApp/Views/Customer/UpdateCustomer.cshtml
@model BusinessManagementSystemApp.Models.Models.CustomerViewModel
@{
    ViewBag.Title = "UpdateCustomer";
}

<div class="container">
    <div class="row">
        <a style="margin-top:2%" href="/Customer/Index" class="btn btn-info"><i class="glyphicon glyphicon-list"></i> Customer List</a><hr />
    </div>
</div>
@if (ViewBag.Message != null)
{
    <h3 class="text-danger" align="center">@ViewBag.Message</h3>
}
@using (Html.BeginForm("UpdateCustomer", "Customer", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    if (Model != null)
    {
        <div class="panel panel-info">
            <div class="panel-heading">
                <h4 class="text-primary">
                    Update Customer
                </h4>
            </div>
            <input type="hidden" name="Id" value="@Model.Id" />
            <input type="hidden" name="IsActive" value="True" />
            <input type="hidden" name="Date" value="@DateTime.Now.ToShortDateString()" />
            <div class="container" style="width:80%; margin-top:3%">
                <div class="col-md-9">
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Customer Name</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.CustomerName, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Customer Code</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.CustomerCode, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Address</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.Address, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Image</label>
                        </div>
                        <div class="col-md-5">
                            <input type="file" class="form-control" name="image" required />
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Email</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.Email, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Contact</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.Contact, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">
                            <label>Loyalty Point</label>
                        </div>
                        <div class="col-md-5">
                            @Html.TextBoxFor(c => c.LoyaltyPoint, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <div class="col-md-3">

                        </div>
                        <div class="col-md-5">
                            <input type="submit" class="btn btn-block btn-success" value="Update" />
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group row">
                        <img src="@Url.Content(Model.ImagePath)" width="90%" height="200" style="border:1px solid red" />
                        <h4 class="text-info" align="center">Image</h4>
                    </div>
                </div>
            </div>
        </div>
    }
}